package cli

import (
	"errors"
	"flag"
	"io/fs"
	"os"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "regenerate the generated parts of docs/")

// TestGeneratedDocs keeps docs/FRAMEWORKS.md and the rule table in
// docs/RULES.md in step with the rule pack. After changing a rule, run
//
//	go test ./internal/cli -run TestGeneratedDocs -update
func TestGeneratedDocs(t *testing.T) {
	fw := run(t, "frameworks", "--format", "markdown")
	fw.expect(t, ExitOK)
	checkDoc(t, "../../docs/FRAMEWORKS.md", "", "", fw.stdout)

	rules := run(t, "rules", "list", "--format", "markdown")
	rules.expect(t, ExitOK, "| `TS-CTR-001` | high |")
	checkDoc(t, "../../docs/RULES.md",
		"<!-- BEGIN generated by `tracestate rules list --format markdown` -->\n",
		"<!-- END generated -->", rules.stdout)
}

// checkDoc compares the text between begin and end markers in path (the
// whole file when begin is empty) with want, or rewrites it under -update.
func checkDoc(t *testing.T, path, begin, end, want string) {
	t.Helper()
	data, err := os.ReadFile(path)
	creating := *update && begin == "" && errors.Is(err, fs.ErrNotExist)
	if err != nil && !creating {
		t.Fatal(err)
	}
	doc := string(data)
	pre, got, post := "", doc, ""
	if begin != "" {
		i, j := strings.Index(doc, begin), strings.Index(doc, end)
		if i < 0 || j < i {
			t.Fatalf("%s: markers %q ... %q not found", path, begin, end)
		}
		pre, got, post = doc[:i+len(begin)], doc[i+len(begin):j], doc[j:]
	}
	if got == want {
		return
	}
	if *update {
		if err := os.WriteFile(path, []byte(pre+want+post), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	t.Errorf("%s is out of date; run: go test ./internal/cli -run TestGeneratedDocs -update", path)
}
