package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"text/tabwriter"

	"github.com/spf13/cobra"

	"github.com/jampanikomal/tracestate/v2/pkg/policy"
)

type controlRow struct {
	Control string   `json:"control"`
	Title   string   `json:"title,omitempty"`
	Rules   []string `json:"rules"`
}

type frameworkRow struct {
	ID       string       `json:"id"`
	Name     string       `json:"name"`
	Controls []controlRow `json:"controls"`
}

func (a *app) frameworksCmd() *cobra.Command {
	var src ruleSource
	var format string
	cmd := &cobra.Command{
		Use:   "frameworks [FRAMEWORK...]",
		Short: "Show which rules evidence which framework controls",
		Long: `Frameworks prints the control mapping of the loaded rule set: for every
framework, each control and the rules that test it. Controls in TraceState's
catalogue that no rule maps to are listed too, so gaps are visible.

  tracestate frameworks DPDPA ISO27001
  tracestate frameworks --format markdown > docs/FRAMEWORKS.md`,
		RunE: func(cmd *cobra.Command, args []string) error {
			rs, err := src.load()
			if err != nil {
				return err
			}
			rows, err := frameworkRows(rs, args)
			if err != nil {
				return usageErr(err)
			}
			switch format {
			case "table":
				return a.frameworksTable(rows)
			case "markdown", "md":
				return frameworksMarkdown(a.stdout, rs, rows)
			case "json":
				return writeJSON(a.stdout, rows)
			}
			return usageErr(fmt.Errorf("unknown format %q (want table, markdown or json)", format))
		},
	}
	src.register(cmd)
	cmd.Flags().StringVarP(&format, "format", "f", "table", "table, markdown or json")
	return cmd
}

func frameworkRows(rs *policy.RuleSet, only []string) ([]frameworkRow, error) {
	mapped := map[string]map[string][]string{} // framework -> control -> rule IDs
	for _, r := range rs.Rules {
		for fw, controls := range r.Frameworks {
			if mapped[fw] == nil {
				mapped[fw] = map[string][]string{}
			}
			for _, c := range controls {
				mapped[fw][c] = append(mapped[fw][c], r.ID)
			}
		}
	}
	ids := map[string]bool{}
	for id := range policy.Catalog {
		ids[id] = true
	}
	for id := range mapped {
		ids[id] = true
	}
	if len(only) > 0 {
		want := map[string]bool{}
		for _, id := range only {
			found := false
			for known := range ids {
				if strings.EqualFold(known, id) {
					want[known], found = true, true
				}
			}
			if !found {
				return nil, fmt.Errorf("unknown framework %q", id)
			}
		}
		ids = want
	}

	var rows []frameworkRow
	for id := range ids {
		controls := map[string]bool{}
		for c := range policy.Catalog[id].Controls {
			controls[c] = true
		}
		for c := range mapped[id] {
			controls[c] = true
		}
		row := frameworkRow{ID: id, Name: policy.FrameworkName(id)}
		for c := range controls {
			rules := mapped[id][c]
			if rules == nil {
				rules = []string{}
			}
			sort.Strings(rules)
			row.Controls = append(row.Controls, controlRow{Control: c, Title: policy.ControlTitle(id, c), Rules: rules})
		}
		sort.Slice(row.Controls, func(i, j int) bool { return policy.ControlLess(row.Controls[i].Control, row.Controls[j].Control) })
		rows = append(rows, row)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].ID < rows[j].ID })
	return rows, nil
}

func (a *app) frameworksTable(rows []frameworkRow) error {
	for i, fw := range rows {
		if i > 0 {
			fmt.Fprintln(a.stdout)
		}
		fmt.Fprintf(a.stdout, "%s (%s)\n", fw.Name, fw.ID)
		tw := tabwriter.NewWriter(a.stdout, 0, 0, 2, ' ', 0)
		for _, c := range fw.Controls {
			rules := strings.Join(c.Rules, ", ")
			if rules == "" {
				rules = "(no rule)"
			}
			fmt.Fprintf(tw, "  %s\t%s\t%s\n", c.Control, c.Title, rules)
		}
		if err := tw.Flush(); err != nil {
			return err
		}
	}
	return nil
}

func frameworksMarkdown(w io.Writer, rs *policy.RuleSet, rows []frameworkRow) error {
	var b strings.Builder
	b.WriteString("# Framework mapping\n\n")
	b.WriteString("<!-- Generated by `tracestate frameworks --format markdown`. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "Every control TraceState's rules evidence, and the rules that test it. Generated from %d rules (%s).\n\n",
		len(rs.Rules), strings.Join(rs.Sources, ", "))
	b.WriteString("A mapping means a violation of the rule is evidence *against* the control. A clean scan shows the specific checks passed; it does not certify the control, which also covers process, people and infrastructure that no code scanner can see.\n\n")
	for _, fw := range rows {
		fmt.Fprintf(&b, "- [%s](#%s)\n", fw.Name, anchor(fw.Name))
	}
	for _, fw := range rows {
		fmt.Fprintf(&b, "\n## %s\n\n", fw.Name)
		b.WriteString("| Control | Title | Rules |\n|---|---|---|\n")
		for _, c := range fw.Controls {
			rules := strings.Join(c.Rules, ", ")
			if rules == "" {
				rules = "—"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", c.Control, mdCell(c.Title), rules)
		}
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// anchor approximates GitHub's heading anchors.
func anchor(heading string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(heading) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		case r == ' ':
			b.WriteByte('-')
		}
	}
	return b.String()
}

func mdCell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
